version: '3.8'

services:
  metadata-service:
    build:
      context: ./backend/metadata-service
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=sqlite:///./test.db
      - AUTH0_DOMAIN=dev-mc721bw3z72t3xex.us.auth0.com
      - API_AUDIENCE=https://cloud-api.rakai/
      - ALGORITHMS=RS256
    ports:
      - "8000:8000"
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  sync-service:
    build:
      context: ./backend/sync-service
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=sqlite:///./test.db
      - API_TITLE=Synchronization Service API
      - API_VERSION=1.0.0
      - API_DESCRIPTION=Service for handling synchronization events
      - AUTH0_DOMAIN=dev-mc721bw3z72t3xex.us.auth0.com
      - API_AUDIENCE=https://cloud-api.rakai/
      - ALGORITHMS=RS256
    ports:
      - "8001:8000"
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
