version: '3.8'

services:
  metadata-db:
    image: postgres:13
    volumes:
      - metadata_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: metadata_user
      POSTGRES_PASSWORD: metadata_password
      POSTGRES_DB: metadata_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U metadata_user -d metadata_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  sync-db:
    image: postgres:13
    volumes:
      - sync_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: sync_user
      POSTGRES_PASSWORD: sync_password
      POSTGRES_DB: sync_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sync_user -d sync_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  metadata-service:
    build:
      context: ./backend/metadata-service
      dockerfile: Dockerfile
    depends_on:
      metadata-db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://metadata_user:metadata_password@metadata-db:5432/metadata_db
      - AUTH0_DOMAIN=dev-mc721bw3z72t3xex.us.auth0.com
      - API_AUDIENCE=https://cloud-api.rakai/
      - ALGORITHMS=RS256
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  sync-service:
    build:
      context: ./backend/sync-service
      dockerfile: Dockerfile
    depends_on:
      sync-db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://sync_user:sync_password@sync-db:5432/sync_db
      - API_TITLE=Synchronization Service API
      - API_VERSION=1.0.0
      - API_DESCRIPTION=Service for handling synchronization events
      - AUTH0_DOMAIN=dev-mc721bw3z72t3xex.us.auth0.com
      - API_AUDIENCE=https://cloud-api.rakai/
      - ALGORITHMS=RS256
    ports:
      - "8001:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  block-storage:
    build:
      context: ./backend/block-storage
      dockerfile: Dockerfile
    volumes:
      - ./backend/block-storage/storage:/app/storage
    environment:
      - PYTHONPATH=/app
    ports:
      - "8003:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  metadata_data:
  sync_data: